### PR TITLE
fix: update acorn to v8

### LINKED ISSUE #54: Update acorn to latest version
When running es-check over my production build, I get this error:

```
          ES-Check Error:
          ----
          · erroring file: ./build/vendor-495a726ca52bcd7d3511.js
          · error: SyntaxError: Parenthesized pattern (124:4651)
          · see the printed err.stack below for context
          ----

          SyntaxError: Parenthesized pattern (124:4651)
```

It seems this might be a bug in the older version of acorn. Is it possible for es-check to use the latest version instead please?

### PR DESCRIPTION
**Pull request by noahnu**
## Fixes

- Fixes #54, updates acorn
- Drops support for unsupported ES4 (not supported by acorn)

----

> Read about referenced issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Replace words with this Pull Request's context.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -83,8 +83,8 @@ prog
         ecmaVersion = '3'
         break
       case 'es4':
-        ecmaVersion = '4'
-        break
+        logger.error('ES4 is not supported.')
+        process.exit(1)
```
Comment (noahnu) [inline index.js:87]: es4 is not supported by acorn

File: index.js [hunk 2]
```diff
@@ -139,7 +139,7 @@ prog
 
     const errArray = []
     const globOpts = { nodir: true }
-    const acornOpts = { ecmaVersion, silent: true }
+    const acornOpts = { ecmaVersion: parseInt(ecmaVersion, 10), silent: true }
```
Comment (noahnu) [inline index.js:142]: I suspect this is why tests were failing. Acorn does a number of strict equality checks where it assumes ecmaVersion is a number, not a string. Without this, it defaults to es3, and so the es5 test fails due to the reserved es3 keyword "char".

**Review by yowainwright — APPROVED** [review]

**Comment by yowainwright** [comment]
@noahnu here we go! 🚀  

Thanks so much for your thoughtful PR. I'll try my best to support this update. 

I'd appreciate your help if you have time. I assume a talented person such as yourself is pretty busy but I guess it never hurts to ask.

Thanks again!
